recipes:
    1:
        name: 'Espaguetis amb tomaquet'
        ingredients:
            basics:
                espaguetis: '100 g'
                tomaquet: '3 cullerades'
                sal: 'un grapadet'
            extras:
                formatge: '1 grapat'
                tonyina: '1 llauna'
        steps:
            - name: step1
              text: 'Posem aigua a bullir a una cassola mitjana'
            - name: step2
              text: 'Tirem els espaguetis i els bullim 3 minuts'
            - name: step3
              text: 'Escurrim els espaguetis'
            - name: step4
              text: 'Els posem a un plat i tirem dues cullerades de tomaquet per persona'
            - name: step5
              text: 'Extra: Afegim una mica de formatge'
    2:
        name: 'Truita de patata'
        ingredients:
            basics:
                patates: '2 unitats'
                ous: '4 ous'
                oli: 'cobrint 1 dit a la paella'
            extras:
                ceba: 'mitja ceba'
        steps:
            1: 'Calentem oli a una paella gran'
            2: 'etc1'
            3: 'etc2'
